### ISSUE TITLE
-i flag not working under VPN environment

### ISSUE THREAD

**Issue by meichengg** [nullt3r/jfscan#2]
Hi, i'm playing hackthebox.eu and i need to do port scanning with specific `utun4` interface which is openvpn config given by them to scan local machine. But it doesn't work as expected rather than running masscan itself.

Scanning with `jfscan`
![image](https://user-images.githubusercontent.com/25204246/164686361-2e473f13-aee1-4842-9dd4-f9a1171829df.png)

Scanning with `masscan`
![image](https://user-images.githubusercontent.com/25204246/164686909-9c70d038-a58e-4189-a9d7-0615768f622f.png)

**Comment by nullt3r** [comment]
Working on fix

**Comment by nullt3r** [comment]
I will look into it.

**Comment by nullt3r** [comment]
Did you ran the jfscan with sudo or with CAP_NET_RAW+ep?

**Comment by meichengg** [comment]
I ran it with `sudo` command, the first image showed very clear.

**Comment by nullt3r** [comment]
> I ran it with `sudo` command

Sorry, it was my stupid question, I can see on screenshot, removed it ;)

**Comment by nullt3r** [comment]
Should be fixed now. Try please.

**Comment by Ch3lLIST4** [comment]
We pulled but the version hasnt been updated, same for the patch.

**Comment by nullt3r** [comment]
> We pulled but the version hasnt been updated, same for the patch.

It should be. Works on my side in lab env.

**Comment by meichengg** [comment]
Thanks, it's fixed and worked like a charm, appreciated.
