### ISSUE TITLE
Show found ports while scanning

### ISSUE THREAD

**Issue by meichengg** [nullt3r/jfscan#4]
Hi, i would like to see found ports while on scanning instead of waiting masscan finishs its progress. Is there any workaround?

For example, after getting many active ports, i want to cancel the progress and get the ports had been found.

![image](https://user-images.githubusercontent.com/25204246/166883614-7fe1290a-3e32-4af8-bd80-55d78e6122ce.png)

**Comment by nullt3r** [comment]
Unfortunately, this feature is not implemented yet. I will look into it in the next release.

**Comment by nullt3r** [comment]
Feature implemented & a lot of new shit.
