### ISSUE TITLE
How to run this tool with 10g nic ?

### ISSUE THREAD

**Issue by neginsadeghi** [nullt3r/jfscan#6]
I need a way to run this tool to send millions of packets per second with 10g nic.
please help me.

**Comment by nullt3r** [comment]
For such task, please use masscan directly (https://github.com/robertdavidgraham/masscan) and follow https://github.com/robertdavidgraham/masscan#pf_ring

**Comment by neginsadeghi** [comment]
but I need Nmap scripting abilities too, so it's better to say let's find out how we can use pfring with jfscan ?!

**Comment by nullt3r** [comment]
This will work with only with Masscan and scans will be much faster, but Nmap will not utilize such throughput as it does not have it's own TCP/IP stack implemented as the masscan does.

**Comment by neginsadeghi** [comment]
Ok, so can you please tell me how we can run Masscan on the 10 GB nic mode and the Nmap on the 1 GB nic mode in the Jfscan tool ?
Or please implement this feature on your tool.
